### PR TITLE
Added SReachTools as a submodule | Updated readme

### PR DESCRIPTION
**Pull request by abyvinod**
Corrected for a typo 'Anesthesia'.
Added SReachTools as a submodule with dependencies clearly explained.
Updated the instructions in README.

### CODE REVIEW

**Comment by abyvinod** [comment]
Vignesh is repeating the instructions to make sure it is repeatable.

**Comment by vigsiv** [comment]
It is repeatable on the following specs using Matlab 2018a, CVX 2.1, Gurobi 7.5.2 (from CVX), and the latest version of MPT: 
image

**Comment by natchi92** [comment]
Thanks Vignesh and Abraham. They have been added to the ARCH-github. Sorry for the delay in response.

**Comment by natchi92** [comment]
Thanks for the update. They have now been merged :)

**Comment by abyvinod** [comment]
Great! Thank you. Will you be updating gitlab repository https://gitlab.com/natchi92/ARCH-COMP/tree/master as well? This is with regards to the pending merge request (https://gitlab.com/goranf/ARCH-COMP/merge_requests/16).

**Pull request merged**
